### ISSUE TITLE
unable to parse host/domain out of resolved FQDN

### ISSUE THREAD

**Issue by Tommi2Day** [aellwein/cert-manager-webhook-netcup#3]
try to get a certificate  based on my netcup domain. Unfortunally it fails as found in cert-manager pod log

```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-mydomain-net-cert
  namespace: cert-manager
spec:
  commonName: 'kube.mydomain.net'
  secretName: kube-mydomain-net-cert
  dnsNames:
    - 'kube.mydomain.net'
    - '*.kube.mydomain.net'
  issuerRef:
    name: letsencrypt-staging-netcup
    kind: ClusterIssuer
```

But it will not fullfill the certificate request. I know i have to wat about 10min to propagate, but its still pending also for a day.

`I0524 18:35:21.307621       1 dns.go:88] cert-manager/challenges/Present "msg"="presenting DNS01 challenge for domain" "dnsName"="kube.mydomain.net" "domain"="kube.mydomain.net" "resource_kind"="Challenge" "resource_name"="kube-mydomain-net-cert-g47p8-752194941-2691253898" "resource_namespace"="cert-manager" "resource_version"="v1" "type"="DNS-01" 
E0524 18:35:21.432257       1 controller.go:166] cert-manager/challenges "msg"="re-queuing item due to error processing" "error"="unable to parse host/domain out of resolved FQDN ('_acme-challenge.kube.mydomain.net.')" "key"="cert-manager/kube-mydomain-net-cert-g47p8-752194941-2691253898"`

a query with dig provides the soa entry set to define, wihich domain is authorative

````
dig @root-dns.netcup.net _acme-challenge.pvekube.tdressler.net. soa txt
;; Warning, extra type option

; <<>> DiG 9.16.1-Ubuntu <<>> @root-dns.netcup.net _acme-challenge.kube.mydomain.net. soa txt
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 22304
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 2585cb374e444deff7dc9acf628d289675d83ae79e8368ec (good)
;; QUESTION SECTION:
;_acme-challenge.kube.mydomain.net. IN TXT

;; AUTHORITY SECTION:
mydomain.net. 86400 IN SOA root-dns.netcup.net. dnsadmin.netcup.net. 2022052356 28800 7200 1209600 86400
````

subdomain kube doesnt exists, but other providers (like hetzner) are still greating an "_acme-challenge.kube" TXT record in mydomain

looking into the webhook code the mentioned dnsName `'_acme-challenge.kube.mydomain.net.` matches  [the regexp](https://github.com/aellwein/cert-manager-webhook-netcup/blob/646491ee565d8f9544c2fd055925c9e73fc6e038/main.go#L139) which triggers this message using a regexp tester
