### ISSUE TITLE
ClusterIssuer rbac problem

### ISSUE THREAD

**Issue by Madic-** [aellwein/cert-manager-webhook-netcup#6]
I created the following ClusterIssuer

```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: netcup-issuer
  namespace: certmanager-system
spec:
  acme:
    email: webmaster@example.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: netcup-le-secret
    solvers:
    - dns01:
        webhook:
          groupName: com.netcup.webhook
          solverName: netcup
          config:
            secretRef: netcup-secret
            secretNamespace: certmanager-system
```

But when requesting a certificate I get the following error:

```
cert-manager/challenges "msg"="re-queuing item due to error processing" "error"="netcup.com.netcup.webhook is forbidden: User \"system:serviceaccount:certmanager-system:certmanager-cert-manager\" cannot create resource \"netcup\" in API group \"com.netcup.webhook\" at the cluster scope" "key"="longhorn-system/cm-storage-tls-jn5t9-848227378-862895558"
```

I installed with the following commands:

```
helm repo add cert-manager-webhook-netcup https://aellwein.github.io/cert-manager-webhook-netcup/charts/
helm install cert-manager-webhook-netcup cert-manager-webhook-netcup/cert-manager-webhook-netcup --namespace certmanager-system
```

The name from the install comand differs from the example in the readme
